"""Centralized PySide6 imports — edit this one file to swap Qt binding."""

from PySide6.QtCore import (
    QAbstractTableModel,
    QModelIndex,
    QObject,
    QPersistentModelIndex,
    QSortFilterProxyModel,
    QStandardPaths,
    Qt,
    Signal,
    Slot,
)
from PySide6.QtGui import (
    QAction,
    QIcon,
    QKeySequence,
    QShortcut,
)
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QMainWindow,
    QMenu,
    QMessageBox,
    QProgressBar,
    QSplitter,
    QStatusBar,
    QTableView,
    QTabWidget,
    QToolBar,
    QTreeView,
    QVBoxLayout,
    QWidget,
)

__all__ = [
    "QAbstractTableModel",
    "QAction",
    "QApplication",
    "QFileDialog",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QKeySequence",
    "QLabel",
    "QLineEdit",
    "QMainWindow",
    "QMenu",
    "QMessageBox",
    "QModelIndex",
    "QObject",
    "QPersistentModelIndex",
    "QProgressBar",
    "QShortcut",
    "QSortFilterProxyModel",
    "QSplitter",
    "QStandardPaths",
    "QStatusBar",
    "QTabWidget",
    "QTableView",
    "QToolBar",
    "QTreeView",
    "QVBoxLayout",
    "QWidget",
    "Qt",
    "Signal",
    "Slot",
]
